version: 2.1

orbs:
  node: circleci/node@5.0.2

defaults: &defaults
  docker:
    - image: ruby:3.1.1

only_main: &only_main
  filters:
    branches:
      only:
        - main

commands:
  configure_runner:
    steps:
      - node/install:
          install-yarn: true
          node-version: '18.6.0'

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - configure_runner
      - run: ./scripts/ci/steps/test.sh

workflows:
  version: 2
  pipeline:
    jobs:
      - test:
          <<: *only_main
