version: 2.1

orbs:
  node: circleci/node@5.0.2

only_main: &only_main
  filters:
    branches:
      only:
        - main

commands:
  configure_runner:
    steps:
      - node/install:
          install-yarn: true
          node-version: '18.6.0'

jobs:
  test:
    docker:
      - image: ruby:3.1.1
      - image: cimg/postgres:14.0
    steps:
      - checkout
      - configure_runner
      - run: ./scripts/ci/common/install_dockerize.sh
      - run: ./scripts/ci/common/wait_for_postgres.sh
      - run: ./scripts/ci/steps/test.sh

workflows:
  version: 2
  pipeline:
    jobs:
      - test:
          <<: *only_main
