---
environment:
  EESE_SERVICE_SERVICE_PORT: "%{hiera('service_port')}"
  EESE_SERVICE_DATABASE_HOST: "%{hiera('database_host')}"
  EESE_SERVICE_DATABASE_PORT: "%{hiera('database_port')}"
  EESE_SERVICE_DATABASE_NAME: "%{hiera('database_name')}"
  EESE_SERVICE_DATABASE_USER: "%{hiera('database_user')}"
  EESE_SERVICE_DATABASE_PASSWORD: "%{hiera('database_password')}"
